export const authActionsConstants = {
  GET_USER_DETAILS: "GET_USER_DETAILS",
  USER_LOGOUT: "USER_LOGOUT",
  ERROR: "ERROR",
  USER_LOGIN_FAILURE: "USER_LOGIN_FAILURE",
  USER_SIGNUP_FAILURE: "USER_SIGNUP_FAILURE",
};
