export const data = [
  {
    id: "n1",
    isPinned: true,
    label: ["class"],
    isArchived: true,
    isTrashed: false,
    title: "Title 1",
    body: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
    createdOn: "25/07/2021",
  },
  {
    id: "n2",
    isPinned: false,
    label: ["work"],
    isArchived: false,
    isTrashed: false,
    title: "Title 2",
    body: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here'",
    createdOn: "25/07/2021",
  },
  {
    id: "n3",
    isPinned: true,
    label: ["work"],
    isArchived: false,
    isTrashed: true,
    title: "Title 3",
    body: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. ",
    createdOn: "25/07/2021",
  },
  {
    id: "n4",
    isPinned: false,
    label: [],
    isArchived: true,
    isTrashed: false,
    title: "Title 4",
    body: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature",
    createdOn: "25/07/2021",
  },
  {
    id: "n5",
    isPinned: false,
    label: ["study"],
    isArchived: true,
    isTrashed: true,
    title: "Title 5",
    body: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.",
    createdOn: "25/07/2021",
  },
];
